version: '3'
services:
  ############## nginx ##############
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - web
    volumes:
      - .:/app:cached
    ports:
      - 80:80

  ############## web ##############
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bundle exec unicorn -c config/unicorn.rb
    volumes:
      - .:/app:cached
    links:
      - redis
      - db
    environment:
      PORT: 3000
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: rails_app_develop
      TEST_DATABASE_HOST: db
      TEST_DATABASE_PORT: 3306
      TEST_DATABASE_USERNAME: root
      TEST_DATABASE_PASSWORD: password
      TEST_DATABASE_NAME: rails_app_test
    ports:
      - 3000:3000

  ############## mysql ##############
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "rails_app_develop"
    volumes:
      - ./tmp/docker/mysql:/var/lib/mysql:delegated
      - ./docker/mysql/config:/etc/mysql/conf.d:cached

  ############## redis ##############
  redis:
    image: redis:latest
